# Generated by Django 4.1.6 on 2023-02-08 04:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.job')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='JobGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.gear')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoped_api.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.user'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'heic'])])),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.job')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.job')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scoped_api.skill')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.user')),
            ],
        ),
    ]
