# Generated by Django 4.1.6 on 2023-03-23 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoped_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='scoped_api.company'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='scoped_api.user'),
        ),
    ]
