# Generated by Django 4.1.6 on 2023-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoped_api', '0002_alter_blog_uid_alter_employee_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
