# Generated by Django 4.1.6 on 2023-02-09 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoped_api', '0003_alter_message_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobgear',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear', to='scoped_api.job'),
        ),
        migrations.AlterField(
            model_name='message',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='scoped_api.job'),
        ),
    ]
