# Generated by Django 4.1.6 on 2023-03-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoped_api', '0003_alter_company_lat_alter_company_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoped_api.company'),
            preserve_default=False,
        ),
    ]
