# Generated by Django 4.1.6 on 2023-03-19 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoped_api', '0004_userskill_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_skills', to='scoped_api.company'),
        ),
    ]
