# Generated by Django 4.1.6 on 2023-02-10 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoped_api', '0004_alter_jobgear_job_alter_message_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='scoped_api.job'),
        ),
        migrations.AlterField(
            model_name='jobgear',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.job'),
        ),
    ]
