# Generated by Django 4.1.6 on 2023-02-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoped_api', '0005_alter_crew_job_alter_jobgear_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_api.user'),
        ),
    ]
